---
title: "Network Demo (VisNetwork)"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard); library(dplyr); library(igraph); library(visNetwork)

#sample of 10,000 Hornets-related Tweets
ttweets <- read.csv("../hornets-sample-nov2016.csv", stringsAsFactors = F)

xx <- subset(ttweets, user_mention_screen_names != "")

y <- xx %>% group_by(handle) %>% summarise(Count=n(),Types=n_distinct(handle))

adjlist <- strsplit(paste0(xx$handle,",",xx$user_mention_screen_names), ",")
edgelist <- cbind(
    unlist(lapply(adjlist, tail, -1L)),                        # col1
    rep(sapply(adjlist, `[`, 1L), times=lengths(adjlist)-1L)   # col2
)
colnames(edgelist) <- c("to","from")

edgelist <- as.data.frame(edgelist, stringsAsFactors = F)

edges <- data.frame(from=edgelist$from, to=edgelist$to)

g <- graph_from_data_frame(d = edges, directed = T)

Totaldeg <- degree(g, mode = "total")
Totaldeg <- Totaldeg[order(Totaldeg, decreasing = T)]
# notice Hornets is dominating the network -- 6247

g2 <- delete_vertices(g, "hornets")

# library(visNetwork)
vg <- toVisNetworkData(g, idToLabel = TRUE)
vg2 <- toVisNetworkData(g2, idToLabel = TRUE)

```

Row {data-height=400}
-----------------------------------------------------------------------

### Text box

You can learn more about ways to customize the network from the [VisNetwork Documentation](http://datastorm-open.github.io/visNetwork/) or [Katya Ognyanova's phenomal R visualization tutorial](http://kateto.net/network-visualization).

Also, to improve these results, consider the following changes:

* Removing peripheral nodes (i.e. not connected to the largest component)

* Remove Retweets (verb == "share"). Note that non-Retweets are verb == "post". This is the formal definition from Twitter/Gnip of a Retweet, and can be slightly different than simply using "RT" in the body of the tweet.

* Color the nodes based on a categorical lable (e.g. Retweets = red, Tweets = blue).

* Add in a section that displays the nodes with the highest connections (in/out degree)


Row {data-height=600}
-----------------------------------------------------------------------

### Keep @hornets in the Network

```{r}
V(g)$size <- 10

visIgraph(g) %>% 
  visInteraction(navigationButtons = TRUE)
```

### Remove @hornets from the Network

```{r}
V(g2)$size <- 10

visIgraph(g2) %>% 
  visInteraction(navigationButtons = TRUE)

```


